spring:
  application:
    name: evm-transaction-processor-service
  datasource:
    url: jdbc:postgresql://db:5432/evm-transaction
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-1.0-initial-schema.xml
  data:
    redis:
      url: redis://redis:6379
web3j:
  client-address: https://mainnet.infura.io/v3/ae2eb3d5fd6b4f38b0232795e4a803b6

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

logging:
  level:
    root: INFO